#!/usr/bin/env python3
import os, json, sys
"""serializes instances to a JSON file\
        and deserializes JSON file to instances"""
class FileStorage:
    """Implementation"""
    __file_path = "file.json"
    __objects = {}

    def all(self):
        """Returns the dictionary"""
        return FileStorage.__objects

    def new(self, obj):
        """sets in the __objects the obj with key <obj classname>.id"""
        FileStorage.__objects[obj.__class__.__name__ + '.' + obj.id] = obj.to_dict() + obj.__dict__

    def save(self):
        """serializes __objects to the JSON file"""
        with open(FileStorage.__file_path, 'w', encoding='utf-8') as output:
            json.dump(FileStorage.__objects, output)

    def reload(self):
        """deserializes the JSON file to __objects only if JSON file\
                exists; otherwise do nothing. If the file doesn't exist\
                no exception should be raised"""
        if os.path.exists(self.__file_path) is True:
            with open(self.__file_path, 'r', encoding='utf-8') as output:
                FileStorage.__objects = json.load(output)
